### ISSUE TITLE
AddOn GoodWe Inverter Solar Sensor does not show any data

### ISSUE THREAD

**Issue by petr-skvor** [mletenay/home-assistant-goodwe-inverter#101]
I installed HACS. In HACS I added the Repository “GoodWe Inverter Solar Sensor (UDP - no cloud)”  v0.9.5. In Settings and Integrations, I found and installed GoodWe. In the GoodWe addon settings, I entered the IP address (static) of my invertet … the connection was Success!

Now in the Integration I select GoodWe (I have "GoodWe GW10K-ET") and it show dashboard overview, all values are “Not available” :o(. When I look in the system log (HA > Settings > Settings > Logs) there is this error:

Logger: custom_components.goodwe
Source: helpers/update_coordinator.py:219
Integration: GoodWe Inverter (documentation, issues)
First occurred: 10:23:57 (5 occurrences)
Last logged: 10:49:22
Error fetching GoodWe data: (‘No valid response received even after 10 retries’, 3)

…I can’t find a solution to this error and empty values :o(. Have you got any idea?

PS: I also instaled "GoodWe SEMS API" v3.4.0 and connect it to Sems Portal with my Power Station Number...and i works fine but support only to values.

**Comment by mletenay** [comment]
It smells like some problem with your network, weak wifi ?
If it was able to configure, it means it received proper response from inverter at least once.
If it fails afterwards, it is most likely some network stuff.
Try to increase log level like:
```
logger:
  default: warning
  logs:
    custom_components.goodwe: debug
    goodwe: debug
```
