### ISSUE TITLE
Change IP in new configuration modal

### ISSUE THREAD

**Issue by fabiopedrosa** [mletenay/home-assistant-goodwe-inverter#102]
Now that we're supposed to configure the integration using the UI, I see no way of updating the inverter IP in the UI. How can I do that?

**Comment by mletenay** [comment]
Just remove the integration and add it back again and during setup enter new IP.
(All the data/entities should kept the old recorded values, since their internal IDs depend on serialNr not IP).

**Comment by fabiopedrosa** [comment]
@mletenay would you approve a PR to make it an option?
