### ISSUE TITLE
sensor.goodwe_inverter unavailable

### ISSUE THREAD

**Issue by epsdaniel** [mletenay/home-assistant-goodwe-inverter#106]
The integration was working perfect!. Since yesterday I have updated to last version PV Inverter change to unavailable. All the rest seem to work perfect.
![pv-inverter](https://user-images.githubusercontent.com/3839983/149117435-f8bf215c-a193-4722-b03f-e4f78451ce6b.jpg)

I have tried to reload the integration, restart ha with no change.

Meantime I have the data in PV Power - sensor.goodwe_ppv but just to report what happened. 

I have goodwe serie EH. 

By the way,.. good job with this integration. Thanks a lot!!

**Comment by mletenay** [comment]
This is actually intentional, the "PV Inverter" sensor was removed, is no longer provided by the integration and can/should be replaced by the goodwe_ppv sensor.
(There were some technical/design reasons for that, required during review process submitting this integration into core HA.)
