### ISSUE TITLE
Goodwe ET

### ISSUE THREAD

**Issue by herrklauss** [mletenay/home-assistant-goodwe-inverter#116]
Hi, thank you for Your work, it is superb.
I have one issues with inverter comm.
I can receive response from inverter randomly, sometimes it takes 5min sometimes hours.

If I will try inverter_test.py, I have this errors.
Inverter is connected thru LAN modul, not WIFI.

Thank you for advice, how solve this problem.
Errors on the picture.
![Goodwe_Errors](https://user-images.githubusercontent.com/100536653/158628369-bf8f6fdc-be46-480a-9ac3-8ae63560459d.JPG)
BR
Vlastimil

**Comment by mletenay** [comment]
There were some reports that the LAN module had some serious issues regarding network reliability and the WIFI was way more stable. But if I'm not mistaken, someone reported there's a LAN module firmware update which resolves the issues.
You should probably try Goodwe support to update your LAN module.
