### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by DewanPieterse** [mletenay/home-assistant-goodwe-inverter#126]
Hello

I updated to 2022.7.0 today and in the logs, this warning was presented:

`Entity None (<class 'custom_components.goodwe.number.InverterNumberEntity'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.`

**Comment by mletenay** [comment]
Thanks for notification, update was committed and will get into next release (soon).
