### ISSUE TITLE
PV showing values when it shouldn't

### ISSUE THREAD

**Issue by oziee** [mletenay/home-assistant-goodwe-inverter#128]
I have a GW5000S-BP. There are no PV panels on this inverter. There is another PV inverter which the CT clamps of the Goodwe read for PV generation for battery charging etc..

the integration sensors for PV show values when I think they should not be

Its currently night here so no sun light at all, but the sensors for PV show values (highlighted in red box)

<img width="270" alt="Screen Shot 2022-07-09 at 9 46 35 pm" src="https://user-images.githubusercontent.com/1471841/178104356-505fbd7a-83d2-4f11-880e-59f9caf51e02.png">

**Comment by mletenay** [comment]
Well, there is absolutely no calculation done at the integration and/or the underlying communication library code related to PV values. They are directly reported by the inverter and presented as is.
They only solution could be to completely remove/hide the PV related values from BPS models, but I'm not really sure I like that idea, so I suggest to accept reality and leave it be ;-)
If you insist on hiding it, please report it to goodwe library repo and I'll see what can be done there...
