### ISSUE TITLE
Export Limit slider using wrong units for GW10K-MS Inverter's 0x9d90 register

### ISSUE THREAD

**Issue by anomaly256** [mletenay/home-assistant-goodwe-inverter#130]
**EDIT**:  Sorry, I seem to have created this issue in the wrong project.. I was looking for the standard integration included in HA.  I'll leave this info here though in case it's useful to this project, seeing as how you mentioned in that discussion that you weren't able to test on an MS device and might not be aware that the register value is treated as percent of rating and not raw wattage.

Hi,

After noticing the export limit slider appearing after a recent update I decided to try dialing it down from the installer's setting of 5kw to test a theory that the inverter's reported production is export+consumption and ignoring dumped energy.  However upon moving this slider from the 50 it seemed to already be at to 4000w I noticed export shut off entirely.  Moving the slider to any other value seemed to have no further effect.

Poking around in SolarGo to read the 0x9d90 register mentioned in the discussion [here](https://github.com/mletenay/home-assistant-goodwe-inverter/discussions/100) and confirming its value being set via the power limit slider in SolarGo, it turns out this value in this register isn't watts at all, it's %. Therefore the slider range should NOT be 0w to 10,000w for a 10kW inverter but 0% to 100%. Or at least, the integration should convert the provided value from the UI into a percentage of the inverter's rating and write that to the register instead of the raw value from the ui.  At the moment this integration's slider only offers increments of +100 so it's not possible to use it to restore the correct value of '50' in my case.  I was able to restore it via SolarGo though and export is working once again.

**Comment by mletenay** [comment]
No problem.
In this custom integration, the problem was fixed quite some time ago.
In standard HA, it got (after some prolonged wait for review) merged yesterday, so should get into next HA release.
