### ISSUE TITLE
Text sensor value is displayed but not logged since graph is displayed also

### ISSUE THREAD

**Issue by Lipown** [mletenay/home-assistant-goodwe-inverter#136]
I am facing an issue when I want to track text sensor history like for example the sun.sun is tracked:
![image](https://user-images.githubusercontent.com/57076375/189605420-7395ba82-ff3f-4bfc-9a32-5ab5f1989a22.png)
However all text sensors in this integration have graph displayed instead of text status changing line graph. How to switch to it please?
![image](https://user-images.githubusercontent.com/57076375/189605309-aca75ccd-9404-4ba7-9923-e6aa7dad9880.png)

**Comment by mletenay** [comment]
Fixed in v0.9.9.7
