### ISSUE TITLE
GW3600S-BP  ECO mode Charge/discharge SCHEDULER

### ISSUE THREAD

**Issue by bubakbrno** [mletenay/home-assistant-goodwe-inverter#139]
Hi, on GW3600S-BP  - switch for ECO mode charge / discharge not work.

It switch inverter to ECO mode, bude each time setups two  schedulers : 

1)  00:00-23:59  DISCHARGE    ACTIVE
2) 00:00-23:59  CHARGE           ACTIVE

That's in conflict and inverte all the time discharge (for charge and for discharge mode).

**Comment by liebefuroscar** [comment]
Same with GW5048-EM

**Comment by svecpetr** [comment]
Could I have a question? Where is possible to change operation mode to Eco charge / discharge mode ... I see only Eco mode. Thanks for reply.

**Comment by mletenay** [comment]
It should be fixed in v0.9.9.9
