### ISSUE TITLE
Watt no kiloWatt

### ISSUE THREAD

**Issue by smithmarius** [mletenay/home-assistant-goodwe-inverter#14]
Hi,

For the ES inverter line 996 should be
        Sensor("e_load_total", 71, _read_power_k, "W", "Total Load", None),
and not 
        Sensor("e_load_total", 71, _read_power_k, "kW", "Total Load", None),

in file 
home-assistant-goodwe-inverter/custom_components/goodwe/goodwe_inverter.py

**Comment by mletenay** [comment]
Fixed.
But it's suspicious as it is 4 bytes value.
Does it provide correct values at all ?
(I don't have ES inverter so I can't verify that)

**Comment by smithmarius** [comment]
Hi, Yes the values is correct but the display only of 'kW' is incorrect the value should be only 'W' . If I was using that much power I would have to get a Aurora Nuclear plant iso a solar installation lol . So the indicator should be W only. The 4 Bytes is only to improve accuracy , maybe also to comply with IEC screen shot before
![Screenshot 2020-10-22 at 06 42 12](https://user-images.githubusercontent.com/39510469/96825556-bc4c4480-1431-11eb-9d2c-b8385750cc3e.png)
after change..Thank you
![Screenshot 2020-10-22 at 07 10 51](https://user-images.githubusercontent.com/39510469/96827363-ba848000-1435-11eb-87ba-b3e1bae05b2f.png)

**Comment by gbyleveldt** [comment]
I need to go check to confirm, but that value SHOULD be kW. That’s the total amount of power the load has drawn since the inverter was installed. 2.6MW is only a few months worth of power.

**Comment by smithmarius** [comment]
Sorry I was wrong it should be kWh not W . The "load" confused me

**Comment by gbyleveldt** [comment]
No worries, I’m pretty sure that the units, as they stand, were correct prior to yesterday’s change. There’s a few of us that’s been using this integration for a few months already.

**Comment by smithmarius** [comment]
> I need to go check to confirm, but that value SHOULD be kW. That’s the total amount of power the load has drawn since the inverter was installed. 2.6MW is only a few months worth of power.

Hi please note there is a difference between MW and MWh the one is snapshot(instantaneous) and the other can be cumulative .  The "h" is important. Just for info GoodweYES is my alias on pvoutput.

**Comment by gbyleveldt** [comment]
Yes, you are correct of course. It’s a little detail issue that should still be fixed. But like I said above, we’ve all been beating our heads against the wall trying to validate the actual daily usage data from UDP as there’s still a discrepancy with SEMS

**Comment by smithmarius** [comment]
I noticed the double count. The SEMS figure excludes the battery being used by inverter while this figured used on this option includes the battery being used as power and show it included.

**Comment by smithmarius** [comment]
I am in ZA

**Comment by gbyleveldt** [comment]
> I noticed the double count. The SEMS figure excludes the battery being used by inverter while this figured used on this option includes the battery being used as power and show it included.

I suspected as much, as the value shows generation in the morning prior to any PV being generated at all. Thing is, in my case, the value shows less generation by the end of the day when compared to SEMS. So, in my case, it’s not a simple matter of just subtracting the battery generation amount to get the PV generation amount. Like I said, this one is still a brain bashed.

You mind if I send you a PM on power forum? I’m having a serious fight with Goodwe because of random inverter restarts, and I just want to compare notes

**Comment by smithmarius** [comment]
No issue see you there. I am 100% sorted on Goodwe no problems.

**Comment by mletenay** [comment]
Unit fixed to kWh

**Comment by smithmarius** [comment]
Thanks Martin working perfectly !
