### ISSUE TITLE
Eco charge mode

### ISSUE THREAD

**Issue by svecpetr** [mletenay/home-assistant-goodwe-inverter#143]
Changing mode to "Eco charge mode" setup a enable timer, that has this settings
- from 0:00 to 23:59 ... OK
- with power of 0% ... BAD ... need to be set to 100% or to user manually predefined value (charging with 0% do nothing, because 0% = 0W)
- battery mode is set to Discharge ... BAD ... Eco charging mode should set mode to CHARGE not discharge :/

For charge limit cannot be used or setted value sensor.batter_charge_limit ... because it is in Ampers and it is readonly value from BMS that show what is the maximum power of charging. So limit of charge in Eco charge mode is absolutely independent on this, because it it percent of power of inventer (for example 10KW inventer has 100% as 10KW and it did not say nothing about ampers of charging, because you need to know the battery voltage.

**Comment by janchlebek** [comment]
This is not a bug - you need to specify what power you want to use for discharging via a service. Not everybody wants to charge with 100% or any other predefined value. The inverter unfortunately tends to forget what the last value was so it is best to simply set this value whenever setting Eco modes in a sequence or using script.

Also there are two modes - whichever you select it does exactly what it is supposed to do - Eco charge mode charges battery, Eco discharge mode discharges. With both you have to set the value in percent of inverter total power (i.e. for ET-10k setting 20 will charge or discharge with 2kW of power.

**Comment by svecpetr** [comment]
Sorry and thanks. Solved... It's a shame there isn't a proper manual
