### ISSUE TITLE
2 integrations 

### ISSUE THREAD

**Issue by rhoracek** [mletenay/home-assistant-goodwe-inverter#147]
Hello, please, add the option of integrating 2 inverters, when adding the second inverter, the integration ends with an error. Thank you.

**Comment by rhoracek** [comment]
[host_2022-12-10T11-23-02.797Z.log](https://github.com/mletenay/home-assistant-goodwe-inverter/files/10199955/host_2022-12-10T11-23-02.797Z.log)
[home-assistant_2022-12-10T11-22-52.092Z.log](https://github.com/mletenay/home-assistant-goodwe-inverter/files/10199957/home-assistant_2022-12-10T11-22-52.092Z.log)
[home-assistant_2022-12-10T11-17-08.294Z.log](https://github.com/mletenay/home-assistant-goodwe-inverter/files/10199958/home-assistant_2022-12-10T11-17-08.294Z.log)
[home-assistant_2022-12-10T11-15-00.820Z.log](https://github.com/mletenay/home-assistant-goodwe-inverter/files/10199959/home-assistant_2022-12-10T11-15-00.820Z.log)

**Comment by mletenay** [comment]
There are no error logs related to goodwe, try to increase log level for the integration.
