### ISSUE TITLE
Interface often not available

### ISSUE THREAD

**Issue by robgiom** [mletenay/home-assistant-goodwe-inverter#152]
Hello,

First of all thanks for the  integration of GoodWe

I'm contacting you because interface with GoodWe Inverter is not work properly since I'm reporting continuing no availability for several seconds and new  connections

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/93553187/210150616-d75ea7f8-ddad-45ec-8c29-130babb50ad4.png">

Could you help me in order to understand the reason why it happen?

Many thanks in advance for your help

**Comment by TheAnT1979** [comment]
i have the same issue

**Comment by Kdonkers** [comment]
Bump, same issue

**Comment by mletenay** [comment]
These connection issues are most likely wifi related.
Increase log level for goodwe module and provide some logs.

**Comment by Kdonkers** [comment]
I have direct connection via LAN module, so this seems incorrect.

**Comment by mletenay** [comment]
Well, actually there are reports of users that LAN is actually less reliable than Wifi.
Cannot neither confirm or deny that personally, but the fact is the network infrastructure is major source of the problems.
If you are using HACS version, you can try to adjust the timeout and retry parameters, for some users it helped.
