### ISSUE TITLE
resetování hodnoty Eco mode power

### ISSUE THREAD

**Issue by hsjirka** [mletenay/home-assistant-goodwe-inverter#153]
předně veliké díky za aplikaci.
Při každém resetování HA se resetuje i nastavení Eco mode power - vždy na hodnotu 0% resp. 3% bez ohledu na jaké hodnotě byl před resetováním HA.
Je možné někde nastavit výchozí hodnotu, aby k tomuto nedocházelo?
ostatní parametry se zachovávají

![4 1](https://user-images.githubusercontent.com/106630756/210573328-48b59fcc-7bae-40b0-a31f-9eec4c6c96a9.jpg)

**Comment by mletenay** [comment]
Should be fixed in v0.9.9.7
