### ISSUE TITLE
voltage vs. frequency device class

### ISSUE THREAD

**Issue by Paja-git** [mletenay/home-assistant-goodwe-inverter#154]
Since HA version 2023.1. I've noticed the startup warnings like: "WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.goodwe_backup_f1 (<class 'custom_components.goodwe.sensor.InverterSensor'>) is using native unit of measurement 'Hz' which is not a valid unit for the device class ('voltage') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author."
Warnings are common for all freq. sensors.

**Comment by mletenay** [comment]
Should be fixed in v0.9.9.6

**Comment by Paja-git** [comment]
Looks fine, thank you.
Pj
