### ISSUE TITLE
Cannot connect to GW3600D-NS

### ISSUE THREAD

**Issue by Marc1200** [mletenay/home-assistant-goodwe-inverter#156]
i am trying to connect to my goodwe inverter, it's the GW3600D-NS but i get this errors in the logger.
is this because the firmware of the inverter is not up to date?

![image](https://user-images.githubusercontent.com/68737063/217539579-45624daf-3cef-4508-89c1-3b2c521665c7.png)

**Comment by mletenay** [comment]
Yes, this looks exactly like the inverter need newer ARM firmware
