### ISSUE TITLE
Eco mode power is unavailable

### ISSUE THREAD

**Issue by sotoniak** [mletenay/home-assistant-goodwe-inverter#158]
In version 0.9.9.7 the Eco charge power setting is unavailable. Furthermore, Eco charge mode and Eco discharge mode cannot be enabled.
Version 0.9.9.6 is working properly

(On device goodwe gw10k-et)
![image](https://user-images.githubusercontent.com/4223741/219176305-83040f12-5c6c-4f95-8479-77d84af12038.png)

Error message (Failed to call service select/select _option. "' not supported between instances of 'None Type' and 'int')

**Comment by mletenay** [comment]
The individual items are enabled upon request to inverter (to check if it is supported by the inverter model/fw).
Since the UDP is unreliable, sometimes it happens that even after 3 retries the proper response is not received.
Could you restart the HA to ensure it was not case like this ?

**Comment by mletenay** [comment]
Actually, there seems to be really a bug there ! Going to fix it.

**Comment by mletenay** [comment]
Fixed in v0.9.9.8
