### ISSUE TITLE
Using the set_work_mode item

### ISSUE THREAD

**Issue by lg0killer** [mletenay/home-assistant-goodwe-inverter#16]
Good day

Firstly I must say I really like the integration a lot! Been using it recently and it's pretty amazing on some of my power-hungry integrations.

Just wanted to know if the set_work_mode can currently be used? I saw in the code section it throws a NotImplementedError so I'm assuming it's not active yet?

If you need to test the toggle, please let me know as well, I might be able to assist if needed.

**Comment by mletenay** [comment]
It is implemented, but still in considered rather unstable/dangerous.
Join us on discord channel - discord.gg/taxywxt we can discuss and improve it there.

**Comment by lg0killer** [comment]
Cool we can do that yes.
