### ISSUE TITLE
Cannot find entity and integration gives ILLEGAL DATA ADDRESS

### ISSUE THREAD

**Issue by Diamantino-Op** [mletenay/home-assistant-goodwe-inverter#165]
I'm trying to connect to my inverter, but it keeps giving me ILLEGAL DATA ADDRESS and the entity is not found,

this is the log:
https://pastebin.com/vzyDsC91

**Comment by mletenay** [comment]
What is you inverter model ?
Since it seems it tries to talk ET protocol but I guess you have ES model ?

**Comment by Diamantino-Op** [comment]
ESA5000

**Comment by mletenay** [comment]
It seems to be a new model which is improperly identified by the code.
Isn't there one more request before the "Connecting to ET family inverter" line ?

**Comment by Diamantino-Op** [comment]
no

**Comment by mletenay** [comment]
Are you able to checkout and execute some python scripts ? (outside HA)

**Comment by Diamantino-Op** [comment]
yes

**Comment by mletenay** [comment]
Great. Can you reach me on our discord ? https://discord.gg/TaXyWXT

**Comment by Diamantino-Op** [comment]
i'm in

**Comment by mletenay** [comment]
I have released fixed underlying library, HACS integration is adjusted and will be released later.
In the meantime, you can re-download the HACS integration (enable "beta" version) and select "master".
