### ISSUE TITLE
GOODWE 3648d-es   entity

### ISSUE THREAD

**Issue by nokia321** [mletenay/home-assistant-goodwe-inverter#175]
Hello. 
I'm from the Czech Republic, I don't speak the language, so I translate in a translator. I need advice on how to configure the GOODWE 3648D-ES photovoltaic inverter. The thing is that it does not show correctly the daily power production and furthermore it is not possible to insert the battery system into the tracking, because the entities are not included.  I don't really understand it, I don't know if I could set it up myself. How complicated is it to get this done.  Thank you Zdenek.

**Comment by nokia321** [comment]
![aa](https://user-images.githubusercontent.com/127352793/226983475-48c3a7e4-cf92-4b83-8c4d-637b6462cfd8.jpg)

**Comment by Plumpop1** [comment]
Zdeňku tvůj inverter neumí počítat baterii vstup a výstup. Jediná možnost je dopsat si entitu a vyčítat ze sems portálu.

**Comment by Plumpop1** [comment]
Zdeňku musíš vyčítat tuhle hodnotu z atributů střídače. Dodělej si do HA Sems portal a tam ty hodnoty najdeš.
Střídač co máš tyhle statistiky nepředává do HA ale pouze na Sems portal.
Jinak jsme rádi že jsi z české republiky :-)

**Comment by nokia321** [comment]
thanks
