### ISSUE TITLE
Nastavení Eco vybíjecí režim nereaguje na nastavení Grid export limit

### ISSUE THREAD

**Issue by hsjirka** [mletenay/home-assistant-goodwe-inverter#184]
cca 1 měsíc zpět mi při spuštění Eco discharge mode docházelo k vyšším hodnotám na výstupu než jsem měl nastaveno Grid export limit. Naopak výstupní hodnotu Active Power Total ovlivňuje zvyšování a snižování Eco mode Power.
Musím mít tedy neustále na měniči zapnuto Grid Export Limit? Nelze toto zapínání a vypínání Grid Export Limit řešit prostřednictvím této aplikace?
Děkuji

**Comment by mletenay** [comment]
set_parameter service with parameter 'grid_export'
