### ISSUE TITLE
Nefunkční GoodWe Experimental

### ISSUE THREAD

**Issue by Bojkas1985** [mletenay/home-assistant-goodwe-inverter#185]
Ahoj @mletenay  
mně a dvou dalším kamarádům přestala fungovat integrace. Mně to padlo dnes kolem 9h a pak přestalo odesílání dat do HA. Žádnou aktualizaci jsem nedělal, kamarád to zrovna dnes aktualizoval. Já jsem na 2023.4.6, kamarád už květnovou verzi. Zkoušel jsme integraci znovu stáhnout, nově načíst, ale píše mi to chyby, že se to nenačetlo, v logu pak jen viz screen.
![image](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/41238303/65a71d9b-43bd-4034-8178-52fb60289c4e)

**Comment by mletenay** [comment]
Nezmenila sa nahodou IP adresa invertera ? PvMaster/SolarGo funguje ?

**Comment by Bojkas1985** [comment]
@mletenay no, to je teoreticky možné. :D Kde se dá vyčíst IP adresa, kterou jsem na začátku zadával?

**Comment by Bojkas1985** [comment]
@mletenay Tak nic, omlouvám se, byla to jen blbá shoda náhod, u mě to byla IP, u druhého kamaráda něco jiného, ale jede mu to, tak jsem myslel, že se to týká více lidí.. Uzavírám, klidně to smaž. Jinak, IP adresy se dají zjistit tady. :) /config/.storage/core.config_entries
