### ISSUE TITLE
Power Limit sensor On/Off

### ISSUE THREAD

**Issue by Bojkas1985** [mletenay/home-assistant-goodwe-inverter#190]
Hi @mletenay 
Would it be possible to add a sensor to show the power limit on/off status? I can toggle them via the set parameter, but I can't base reliable automation on it because I don't know if the power limit is on or not.
Ivica

Edit: i use get_parameter and create number helper, now I can read power limit. But, original sensor be better. 😊
![Screenshot_20230527_182402_Home Assistant](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/41238303/798edfc2-7faa-480d-bcec-0a503ba6bf50)
![Screenshot_20230527_182318_Home Assistant](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/41238303/ad4fabf2-2445-4c55-b897-c849ce8ec5f1)

**Comment by mirecekd** [comment]
Check issue https://github.com/mletenay/home-assistant-goodwe-inverter/issues/167
