### ISSUE TITLE
House Consumption is wrong on low load

### ISSUE THREAD

**Issue by smileyman-1** [mletenay/home-assistant-goodwe-inverter#191]
If consumption is low and there is no pv-input (at night), the House Consumption value is incorrect.
<img width="382" alt="image" src="https://github.com/mletenay/home-assistant-goodwe-inverter/assets/55857747/f04f2eea-a799-45ff-8076-6ce6616bf237">
At night, a generation of 15 watts is detected in this way. 

On-grid Export Power shows the same wrong value. (In PV-Master the value is correct.)
On-grid Power and Plant Power, on the other hand, usually - but not always - shows at this time the correct value. (But this values are always positiv and do not switch to minus for importing)
<img width="243" alt="image" src="https://github.com/mletenay/home-assistant-goodwe-inverter/assets/55857747/ffeb1d89-1d7f-4c65-b501-d1d73966b8ab">

When the load is higher House Consumption shows the correct values.
<img width="1673" alt="image" src="https://github.com/mletenay/home-assistant-goodwe-inverter/assets/55857747/ff2bf059-29cf-4268-b7c0-65b993d2da71">
<img width="1672" alt="image" src="https://github.com/mletenay/home-assistant-goodwe-inverter/assets/55857747/c7051b16-2e40-4ed2-806d-1bcf39bd106c">

Inverter: GW3068-EM

**Comment by Paja-git** [comment]
The house consumption is a calculated value. PV1Power+PV2Power+BaterryPower-ActivePower. ModBus registers are read sequentially, the inverter's probes have some precision also. So, small calc errors can happen.

**Comment by nuitari83it** [comment]
Same "problem" here.
What is exactly the difference between "house consumption" and "plant power"? What is exactly measuring the second one?

**Comment by Paja-git** [comment]
> The latest released Goodwe integration for HA with a GW3048-EM inverter

OK, it explains a lot - sensor is listed in the es.py. The Plant power is calculated value:  the on-grid + backup power sensors. The House consumption calcutates PV1,PV2, Battery, Export.

**Comment by nuitari83it** [comment]
thanks for the explanation, so basically it doesn't count the photovoltaic production influence
