### ISSUE TITLE
Firmware version (ARM) is wrong

### ISSUE THREAD

**Issue by smileyman-1** [mletenay/home-assistant-goodwe-inverter#195]
In device information dialog the (ARM) firmware version is wrong: (Digits are swapped)

<img width="251" alt="image" src="https://github.com/mletenay/home-assistant-goodwe-inverter/assets/55857747/276b7f38-a7d7-4332-8275-3211bf87c6f4">

correct is (from PV-Master / SolarGo-App and firmware file): 17.17.53 
-> the ARM version is not 35, correct ist 53

**Comment by nelgi** [comment]
a bit offtopic, but how you get new fw versions? mine is 14.14.10:

![image](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/46314439/4d7c7407-896b-4360-8a63-7d142354d77a)

**Comment by smileyman-1** [comment]
Open a ticket at Goodwe (and wait, wait, wait, wait ;-)) oder do it by yourself: https://www.photovoltaikforum.com/core/attachment/342066-bluetooth-firmware-update-string-storage-de-v002-pdf/

**Comment by wesleyv010** [comment]
I have a new inverter last month. The firmware version is 19.19. 51.

Is this firmware more recent and better?

**Comment by nelsnels** [comment]
> Open a ticket at Goodwe (and wait, wait, wait, wait ;-)) oder do it by yourself: https://www.photovoltaikforum.com/core/attachment/342066-bluetooth-firmware-update-string-storage-de-v002-pdf/

Hi @smileyman-1 , thank you for your work and for this document! Did you have the chance to update an hybrid inverter, such as series ET? I haven't found a way to use the SolarGo app to upgrade the firmware using the files in the Google drive. The app only suggest an automatic update, which is surprisingly stuck in ARM 7 in my case. Is there another way to perform this update?

As you suggested, I also open at ticket at Goodwe and I'm currently wainting, wainting, wainting...

**Comment by smileyman-1** [comment]
Hi @nelsnels,
I only have one from the EM series and one from the SDT series.
With the SDT G2 I connect via Solar Go via WLAN and download the bin file from Google Drive beforehand. However, this must be renamed, otherwise the name is too long. I can select this file via 'Manual file selection' and flash it.
With the EM inverter, the whole thing only works via Bluetooth dongle. Unfortunately I do not have a Bluetooth dongle.

**Comment by mletenay** [comment]
Closing the issue as obsolete/invalid.
There is actually no bug there, the value is taken as it is.
It's juts encoded in hex and accidentally 53 = 0x35 ;-)
