### ISSUE TITLE
PV Modules Power Sensor

### ISSUE THREAD

**Issue by kolossboss** [mletenay/home-assistant-goodwe-inverter#2]
Hi,

thanks a lot for this Integration! Works fine so far.
At this moment I‘m using the Sems Portal Integration. There I have a Sensor for the actual production power output of the PV modules in Watt.
I cant found this sensor here. Maybe its possible to caculate with „goodwe_pv1_current“ and „goodwe_pv1_voltage“. But I‘m not sure how to do that in HA. I think its easier to provide a sensor with that value.

Thanks a lot and great work!

**Comment by mletenay** [comment]
Done.
Calculated "PV1 Power", "PV2 Power" and "PV Power" sensors were added to ES inverter (ET already provided them).
