### ISSUE TITLE
Export limit GW8000-DT not working

### ISSUE THREAD

**Issue by TomStarren** [mletenay/home-assistant-goodwe-inverter#209]
Hello, 
I want to control the power export settings (via HA) for my GW8000-DT inverter. I've tried the steps mentioned in [issue 100](https://github.com/mletenay/home-assistant-goodwe-inverter/discussions/100). 

But after I change the power limit seting on the inverter itself [page 26 in this pdf](https://www.originenergy.com.au/wp-content/uploads/UserManual-GW-DT-SDT-B-UM006.pdf), the SolorGo app reports unstable connection each time I connect. Distance to the inverter doesn't matter and the WiFi connection seems stable.

Anyone an idea what I can try to enable this feature?

Cheers,
Tom

**Comment by mletenay** [comment]
Lot of functionality depends on more recent firmware versions.
If that functionality is working for someone with your inverter model, asking support for firmware update may help you.
