### ISSUE TITLE
3 MPPT Inverters, wrong assign PVx entities

### ISSUE THREAD

**Issue by AT622CZ** [mletenay/home-assistant-goodwe-inverter#217]
Hi,
GW25K-ET or GW30K-ET has SIX PV inputs and 3 MPPTs. Each input has separate sets of registers. Voltage of PV1 and PV2 (PV3, PV4 and PV5, PV6)  are same, but Currents are measured individually.  I have two strings connected to the first and second MPPTs, inputs 1 and 3.  Correct values I need read from PV1, PV3. PV5 is unconnected now.

![gw25-test](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/107034857/5d184413-fa63-4f2a-933f-b541c349a99b)

Best regards
Michal Patek

**Comment by mletenay** [comment]
Hmm, this seems odd.
The known map of modbus registers have 4 sets of voltage/current/power for potential 4 MPPTs.
See https://github.com/marcelblijleven/goodwe/blob/90909e06c6fa2088379503aca10e27a12c397e87/goodwe/et.py#L22
If these report wrong valules and there are different/additional registers for ETT inverters, well, I do not know them.

**Comment by mletenay** [comment]
For reference - https://github.com/home-assistant/core/issues/95703

**Comment by AT622CZ** [comment]
> Hmm, this seems odd. The known map of modbus registers have 4 sets of voltage/current/power for potential 4 MPPTs. See https://github.com/marcelblijleven/goodwe/blob/90909e06c6fa2088379503aca10e27a12c397e87/goodwe/et.py#L22 If these report wrong valules and there are different/additional registers for ETT inverters, well, I do not know them.

Throw modus, for MPPT 1 and 2 we can use this set of register (PV1-PV4). BUT! Only Voltage and current (seams)!. Correct Voltages and Currents I can read from PV1 and PV3 regs, MPPT 1 power is in PV1, MPPT2 is PV2.
(on pictures: today is rainy, dark, MPPT 3 is not connected now).

Adresses of PV5 and PV6 I don't know :-( GW support is silent.


![gw25-PV3-PV4](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/107034857/280eebd6-ff73-4262-acc4-484f7bcaffef)

![gw25-modbus](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/107034857/c35c3384-d33b-41e6-ae21-f3b8287e9589)

**Comment by mletenay** [comment]
Can you monitor all 4 those V/A/W values via SolarGo mobile app ?

**Comment by AT622CZ** [comment]
SolarGo shoes V/A, all 6. But as I wrote PV1-PV4 are same registers as on 10kW GW. MPPT1 is PV1, PV2, MPPT2 is PV3-PV4. MPPT3 we don't know adresses. Power for MPPT1 is PV1, MPPT2 is PV2, MPPT3 is PV3

![Screenshot (28  10  2023 10_10_25)](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/107034857/449cfbd9-fa20-480e-b507-eacf006d2310)

**Comment by mletenay** [comment]
See https://github.com/marcelblijleven/goodwe/issues/62
There was some progress with ETT inverters, once I'll release the library I'll adjust the HA integration

**Comment by sergioafeo** [comment]
Thanks @mletenay. I have a similar issue with  GW15ET. It has 2 MPPTs and 4 inputs. Strings are connected to inputs PV1 and PV3. Both pyhton lib and HA integration show up to PV2 only.

**Comment by mletenay** [comment]
The v0.9.9.13 was just release and it contains proper support for ETT, incl. 2nd battery, pv1-6 and mppt sensors.
