### ISSUE TITLE
Fast Charging not working on ES models

### ISSUE THREAD

**Issue by drydenmike** [mletenay/home-assistant-goodwe-inverter#218]
Hey. Just to let you know I appreciate the work you're doing here.
Having said this, I have a ES model and fast charging is not working with any of the parameters mentioned here: https://github.com/mletenay/home-assistant-goodwe-inverter/issues/150

> 
> The "fast charging" inverter feature should be reachable in v0.9.9.7 now.
> It is not exposed in UI anywhere, but you should be able to apply it by calling set_parameter service - there are now parameters fast_charging (0-1), fast_charging_soc (10-100), fast_charging_power (10-100)

Do you think this might be different depending on model/software version?

**Comment by mletenay** [comment]
Yes, it is possible it is firmware/model specific and since I do not have direct access to different inverters I cannot test/fix that (if possible at all).

**Comment by drydenmike** [comment]
Is there something that I can do at my end to extract this information?

**Comment by traveler6666** [comment]
Hi,

I really love this featrue. However, shortly after I set up the fast charging service, I can't set the SOC anymore. I think there was an update.
I am getting an unpexted error message and the protocoll says: goodwe.exceptions.RequestRejectedException: ILLEGAL DATA VALUE if the value is e.g. 81 or input_number.fast_charging_soc.

The code is:

service: goodwe.set_parameter
data:
device_id: b9cb944ba3a1382249238c4a2523b698
parameter: fast_charging_soc
value: states("input_number.fast_charging_soc")

Is there an error in the code or a bug in the integration, as it worked before?

**Comment by drydenmike** [comment]
This is working in the latest versions.
