### ISSUE TITLE
Self-use load

### ISSUE THREAD

**Issue by lexaplexa** [mletenay/home-assistant-goodwe-inverter#221]
Hello,

recently I found a diag message "_Self-use load light_". In last month there was a different behaviour with my inverter (ET 8k) and from the statistic I see that the energy from battery is not fully used. Some minor power is still imported from grid even if battery is fully charged. Before I reached 98% self-sufficiency, now I reach maximum 80% on sunny days when nobody is home.
This behaviour started after I played a little bit with eco modes from current Goodwe integration in HA. 

![image](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/19929415/52d6d000-d4f7-43d3-a3e1-b069df5538bd)

Obviously I change something, but I am not avare of what. Has anybody same experience and solved it somehow?

**Comment by shiner66** [comment]
I am having some issues with SOC indication aswell since i started playing with eco mode to charge at night. @mletenay is that possible?
