### ISSUE TITLE
Stop charging while still in Eco Charge Mode

### ISSUE THREAD

**Issue by PumpaXXL** [mletenay/home-assistant-goodwe-inverter#227]
Hi and thanks for the amazing HACS!

One issue though, and I am talking to a guy with the same config GW 10k Plus with the same problem. When set the Eco charge mode by HA automation during the night, GW droppes off the charging at random time. It is still in the Eco charge mode but the battery is not charging. 

It has happened 4 times in the last week. Target SOC is set to 100%, charging shuts off at different SOCs, today at 61%. The only thing I traced is that the diag status code changed from 33 554 816 to 33 554 880 at that point, but I can't find those codes anywhere so I don't know what they mean. 

Thanks!

**Comment by mletenay** [comment]
Meaning of diag status bits is here - https://github.com/marcelblijleven/goodwe/blob/af031d8fd1b4a630362576a7a1df049b4f0da170/goodwe/const.py#L201
