### ISSUE TITLE
PV3 and PV4 dont show 

### ISSUE THREAD

**Issue by gigi2485** [mletenay/home-assistant-goodwe-inverter#233]
Inverter 15k et:
the entities for PV3 and PV4 are not displayed for me.
In SolarGo they are displayed as normal.
<img width="278" alt="1" src="https://github.com/mletenay/home-assistant-goodwe-inverter/assets/24621676/c1183bb9-c4b4-40e0-8970-5cfb9058aec8">
<img width="284" alt="2" src="https://github.com/mletenay/home-assistant-goodwe-inverter/assets/24621676/c1c4c612-07bc-42af-acf5-5c7feb1a3ce2">

The current for the MPPT is also specified in watts 
<img width="274" alt="3" src="https://github.com/mletenay/home-assistant-goodwe-inverter/assets/24621676/d554bad0-5924-4c61-88c2-f6e62acdddf3">

thx

**Comment by mletenay** [comment]
Indeed. 
There is a copy/paste mistake in the library using power instead of current. I'll fix it.
As for the pv3/4, there is problem as well (actually a confusion of pv and mppt values).
It would be great if you could provide the raw responses from the logs so I can add them to unit tests.

**Comment by mletenay** [comment]
Fixed in v0.9.9.14

**Comment by coreYalfons** [comment]
I have the same issue with current version pv3 and pv4 missing
