### ISSUE TITLE
cell voltage scale error

### ISSUE THREAD

**Issue by tacoroumen** [mletenay/home-assistant-goodwe-inverter#244]
battery_max_cell_voltage      : Battery Max Cell Voltage = 334.0 V
battery_min_cell_voltage      : Battery Min Cell Voltage = 333.8 V

This should be 3.340V and 3.338V

Inverter: GW6000ES20

**Comment by mletenay** [comment]
Indeed. It is reported in mV not V.
Could you provide me the raw response from the log files ? (All my test samples contain 0 there ...)

**Comment by tacoroumen** [comment]
Where would this log be? i cant find it @mletenay

**Comment by mletenay** [comment]
HA log, just enable debug on integration and it should log raw hex values

**Comment by tacoroumen** [comment]
it doesnt show any logs, where does it log these logs?

**Comment by mletenay** [comment]
Fixed in v0.9.9.14
