### ISSUE TITLE
PV1 Voltage = PV2 Voltage and PV2-Currunt alway 0A @ 3-Stringed GW25ET

### ISSUE THREAD

**Issue by hbpv** [mletenay/home-assistant-goodwe-inverter#245]
Hi

We've two major Problems with values:

1. PV1 Voltage is alway the same as PV2 Voltage, but the Strings are strongly different. Please see the screenshot. Is it possible that there is an copy-paste mistake in polling the same values inside the script?

2. PV2 Current stay always at 0. As this String is producing >3kwh, this is wrong.

Thanks and best,
Max

![Pv2-current-always-0](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/138022041/605f311c-a22d-40f1-a635-278d47623fda)
![Pv1-voltage=Pv2-voltage](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/138022041/0bfc4912-c24c-4f75-b40e-62314a3f037e)

**Comment by hbpv** [comment]
Okay, so the entities we get are wrong?
The Inverter has 6 PV Ports
1+2 = PV1
3+4 = PV2
5+6 = PV3

Our first String is on Input 1 (PV1-1)
Our second String is on Input 3 (PV2-1)
Our third String is on Input 5 (PV3-1)

In the home assistant integration, the way your argument, we should get the entities PV1 + PV3 + PV5.
But it only shows 1,2,3. Also, when they have the same Voltage, the other values should be the same regarding your idea, but they're not.

Please see attached the Screenshot for the integration.

![image](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/138022041/4c659792-62cf-41c4-b428-2d8181d4ed84)
![image](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/138022041/b634c8af-a917-4433-8145-a96cdb42d9cf)

**Comment by hbpv** [comment]
Here you’ve got the sems values, where it shows correctly 3 different strings and their voltages etc

![IMG_3757](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/138022041/ed1ac65c-dcb0-4078-8639-f19999effe6e)

**Comment by mletenay** [comment]
Well, what I know is there is no copy/paste mistake in the code - see for yourself: https://github.com/marcelblijleven/goodwe/blob/master/goodwe/et.py
The rest is responsibility of inverter what values it provides.

**Comment by mletenay** [comment]
... and the current integration does not have the latest library code yet, so you may not see the pv5+ sensors.
If you are able, try the library directly and run inverter_check.py to see all values inverter reports.

**Comment by hbpv** [comment]
Okay.. And now? How could I further help to get this resolved?

As you can see in the SEMS Screenshot, there are 3 different values. So maybe we should check, why the integration/inventer is not resolving the ports that are connected (PV1-1 = PV1) + (PV2-1 = PV3) + (PV3-1 = PV5). Maybe wrong pull of modbus registers? In the et.py i see a lot more possible PV's up to 16.

Can i somewhere check/log which values are provided? Maybe we can there find the problem.

**Comment by hbpv** [comment]
> ... and the current integration does not have the latest library code yet, so you may not see the pv5+ sensors. If you are able, **try the library directly** and run inverter_check.py to see all values inverter reports.

Okay.. and how to update our library? Could give me a short how to? Thanks

**Comment by mletenay** [comment]
I will release next version of the library probably over the weekend and then adjust the HA integration as well.

**Comment by hbpv** [comment]
> I will release next version of the library probably over the weekend and then adjust the HA integration as well.

Okay.. i just installed the moist recent version of hacs-goodwe from you, but problem persists. Is this the same release channel?

**Comment by hbpv** [comment]
For your release, please be aware that with hacs integration:

MPTT entities are working fine (all 3 with correct values) BUT MPPTX Current are W(Watt) instead of A(ampere), see screenshot
![image](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/138022041/fe287adf-2e82-47a0-bcbc-11540ea780bf)

And:

As i showed you before, all (exept PV4 is missing completly??) PV's are showing, but with wrong Voltages:

Starting with

(MPPT1) PV1 - Voltage and Current OK
(MPPT1) PV1 - Voltage and Current OK
(MPPT1) PV1 - Voltage and Current OK


![image](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/138022041/14956cef-7140-42f6-b3c7-1e5b92d2702c)
