### ISSUE TITLE
GW15K-ET cannot connect with version 0.9.9.14

### ISSUE THREAD

**Issue by Brumhilde** [mletenay/home-assistant-goodwe-inverter#254]
Using 0.9.9.14 I get an error in the log that Goodwe platform is not available. 0.9.9.13 is working fine.
Inverter GW15K-ET.

**Comment by mletenay** [comment]
Update HA to 2024.2.1 and/or show the log

**Comment by Brumhilde** [comment]
Ohh.. Thanks. I think I'll wait for https://github.com/mletenay/home-assistant-goodwe-inverter/issues/249 before I update anything.
