### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'goodwe'

### ISSUE THREAD

**Issue by mareklab** [mletenay/home-assistant-goodwe-inverter#26]
HA shows in log files:

`No 'version' key in the manifest file for custom integration 'goodwe'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'goodwe`

**Comment by mletenay** [comment]
This is fix since https://github.com/mletenay/home-assistant-goodwe-inverter/commit/9ca63eeff62503a4f6bf0d5b3a2a3fbe76c0397e #
