### ISSUE TITLE
Entities today will stop working after midnight

### ISSUE THREAD

**Issue by mletenay** [mletenay/home-assistant-goodwe-inverter#281]
### Discussed in https://github.com/mletenay/home-assistant-goodwe-inverter/discussions/279

<div type='discussions-op-text'>

<sup>Originally posted by **sitvesep** May 10, 2024</sup>
The last two updates are causing me to get an error as soon as it is midnight, when the entity states are supposed to be reset: **the entity is not numeric**.  Only entities **today** will stop working.  If I revert to  v0.9.9.17, everything is fine.

![battery](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/136500212/f097b7ce-622b-460d-90c8-183bec4199fc)
![PV](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/136500212/9df9420e-933c-4c2d-b9f8-bc94d0abf8ac)

This problem I was also noticed by some people on the FB group about PV. 

Does anyone also have experience with this error ?

GW10K-ET
Firmaware: 04029-11-S11/02041-27-S00
 

Thank you

</div>

**Comment by mletenay** [comment]
Well, I liked the 0 value too, but strictly technically speaking, that is not what inverter reports.
Inverter says N/A (0xFFFF/-1).
The hacky conversion to 0 was replaced in the library with None to consolidate behavior of Total and Daily sensors.
And the Total has to return None, otherwise HA's energy dashboard goes completely nuts ...
I need to find a proper way/place where to put None->0 for daily sensors only, which I do not like too much ...

**Comment by Legnava89** [comment]
Unfortunately, I can't upgrade to a higher version until the issue is
resolved somehow.
Why does it work without problems in v0.9.9.17 and not in the new version?
The inverter keeps the same status.

po 13. 5. 2024 v 12:21 odesílatel mletenay ***@***.***>
napsal:

**Comment by mletenay** [comment]
Yes, the inverter behaves the same - returns N/A.
But the python library code was consolidated/fixed and now the N/A is propagated to HA.
As said above, the fact it worked before was kinda hack.

**Comment by Legnava89** [comment]
If it can't be returned, I have a workaround via node-red that updates the status from unknown to 0.
But you have to put python_scripts in HA.
I'll try after midnight tonight. In HA development, this works through node-red.

**Comment by mletenay** [comment]
Errrrrr, actually I was wrong above.
The inverter reports 0 not N/A.
I just made a mistake when fixing the DT behavior ...
Fix is on the way ...

**Comment by Legnava89** [comment]
Thank you very much. I will praise you everywhere

**Comment by sitvesep** [comment]
thanks for checking the error and fixing it. I believe it will help a lot of people. thanks for your work, coffee is on the way.

**Comment by mletenay** [comment]
Fixed in v0.9.9.20

**Comment by Legnava89** [comment]
After the new update, the complete cell integration does not work.
![Screenshot_20240517_001851_Home Assistant](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/145229528/20ab57f8-e291-46f0-b8a7-c694d3fcd89c)
![Screenshot_20240517_001911_Home Assistant](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/145229528/b736d8bd-6ebc-4234-832c-dcdc55bbe3f9)
![Screenshot_20240517_001917_Home Assistant](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/145229528/1aaf60d5-b002-4427-a99b-f3be0994a528)

**Comment by sitvesep** [comment]
yes, the integration has completely stopped working for me as well. downloaded the version back and it's ok

[home-assistant_goodwe_2024-05-16T22-26-37.131Z.log](https://github.com/mletenay/home-assistant-goodwe-inverter/files/15341637/home-assistant_goodwe_2024-05-16T22-26-37.131Z.log)
![IMG_1315](https://github.com/mletenay/home-assistant-goodwe-inverter/assets/136500212/2921759a-f5d9-427a-83b7-7582cab241b3)

**Comment by sitvesep** [comment]
I tried to delete the device and add it again and it works

**Comment by mletenay** [comment]
Yeah, I forgot the need for settings migration, v0.9.9.20 was broken in this aspect.
v0.9.9.22 is fixed and works without need to re-add integration.
