### ISSUE TITLE
Stop updating

### ISSUE THREAD

**Issue by JoseMadbird** [mletenay/home-assistant-goodwe-inverter#283]
Since 1 week more or less, Integration stop updating data from inverter...... if i recharge the integration, start upting but after some minutes stop........

**Comment by AlienVi22** [comment]
Same problem on integration GW10K-ET. Integration reload will help for a few hours...

**Comment by mletenay** [comment]
Indeed, I have found and issue within the new "fragment handling", fix is on the way ...

**Comment by mletenay** [comment]
Fixed in v0.9.9.25

**Comment by JoseMadbird** [comment]
> Fixed in v0.9.9.25

Working for now, thanks!!!
