### ISSUE TITLE
Not working correctly on 0.9.9.24

### ISSUE THREAD

**Issue by midadami** [mletenay/home-assistant-goodwe-inverter#284]
I have 2 inverters. One is D-NS (DT) and other is D-ES (ES). 

Since few last updates the D-ES (ES) is not updating on its own so I have to reload integration to get new values.

D-NS (DT) inverter is working without a problem.

Happens every few hours, I will post logs when it happens again.

**Comment by mletenay** [comment]
Enable debug logging and provide the logs please.

**Comment by AlienVi22** [comment]
Same problem with GW10K-ET

**Comment by beilm** [comment]
I do have the same problem with the GW5048-EM

**Comment by mletenay** [comment]
Probably the same problem as in #283, fix will be there soon.

**Comment by mletenay** [comment]
Fixed in v0.9.9.25
