### ISSUE TITLE
Scan Interval has no effect using TCP

### ISSUE THREAD

**Issue by garv3** [mletenay/home-assistant-goodwe-inverter#312]
I am using the experimental version and recently switched to the new WiFi/LAN 2.0 Dongle and changed the protocol to TCP.
What I found is, that the "Scan interval" setting seems to be useless. It is set to 2 seconds but the sensors update every 20 seconds.
![image](https://github.com/user-attachments/assets/f23d95af-b440-43bc-8e18-faf45315e44e)
![image](https://github.com/user-attachments/assets/4902bf00-01b9-4c59-82de-d6ea7da5b35f)
When I used UDP with the old module, everything worked fine when updating every other second.
Any suggestions?

**Comment by crispe** [comment]
This is not an issue with the integration. It is the firmware on the WiFi/LAN module that will report the same values during 20 seconds. So even if the integration in scanning every couple of seconds it keeps will appear that it is not since no values change.

**Comment by garv3** [comment]
Oh, wow. This is a joke. What is goodwe doing here?
