### ISSUE TITLE
Bad status of Today Battery Charge FW 1229

### ISSUE THREAD

**Issue by MildaC** [mletenay/home-assistant-goodwe-inverter#325]
After updating the firmware of the Goodwe 10KN-ET Plus inverter to version 1229, there is a problem with the Today Battery Charge entity, which measures about half the value. This was fine with version 1228. Pylontech Force H2 battery.

**Comment by janstepanek159** [comment]
Hi, same issue here with BYD HVS battery.

**Comment by Dejv555** [comment]
Have the same problem with pylontech batteries.
