### ISSUE TITLE
House_comsumption less than backup

### ISSUE THREAD

**Issue by scrhall** [mletenay/home-assistant-goodwe-inverter#37]
Hi I have GW5048D-ES
The consumption of the house at night with low load, appears less than the consumption of the backup, should not be greater or equal? House _consumption includes backup doesn't it? 

![Screenshot_2021-07-28-01-36-40-512_com android chrome](https://user-images.githubusercontent.com/5793824/127241278-72c79427-bbf9-4475-b469-6824f6066580.jpg)

**Comment by mletenay** [comment]
At the moment the house_consumption is calculared as ppv1 + ppv2 + pbattery1 - pgrid.
Assuming the pgrid is the power at meter (CT clamp).
If the pgrid is actually power on inverter output, than it may not represent correct calculation and probably also pback_up should substracted.
I have no access to ES inverter so can't verify it, can you somehow validate this theory ?
Or is there reported sensor represented the power at meter ?

**Comment by scrhall** [comment]
I can confirm that house consumption not take account all the W consumed. If I turn on a fan connected to backup, for example, I only see the W reflected in the backup sensor and not in the house consumption sensor.

**Comment by scrhall** [comment]
![Screenshot_2021-09-03-02-50-44-834_com android chrome~2](https://user-images.githubusercontent.com/5793824/131934805-608e5d8a-2aa3-4044-94c5-73b7bc134419.jpg)
This is the data, if I turn off all breakers of the non-critical part of my installation
![Screenshot_2021-09-03-02-53-50-359_com android chrome~2](https://user-images.githubusercontent.com/5793824/131934807-64056f16-ed0f-4a2e-9ca4-f8682b6e7d67.jpg)
If I turn on for example a ceiling fan (in the backup output), only the backup sensor goes up
![Screenshot_2021-09-03-02-55-51-775_com android chrome~2](https://user-images.githubusercontent.com/5793824/131934808-439a2c9b-2819-4d86-83c6-4f4e0c2f3075.jpg)
I add another capture of the data, none of them match

**Comment by scrhall** [comment]
![Screenshot_2021-09-03-08-35-42-622_com android chrome~2](https://user-images.githubusercontent.com/5793824/131961804-d7f54263-5a20-4dbd-bf33-748ff1cc8943.jpg)
Two additional screenshots, the first, is with the normal morning load. You can also see the info showing pvmaster
![Screenshot_2021-09-03-08-32-04-418_com goodweforphone~2](https://user-images.githubusercontent.com/5793824/131961808-135b9972-a46e-4562-a547-6ad62b04da27.jpg)
This last screenshot is completely disconnected from both the backup and the ac in


Where does that consumption of 80w come from?, is it the consumption of the investor himself?  Even so, neither in pvmaster nor in ha are the data coherent

**Comment by ziporah** [comment]
self consumption without backup should be <13W for your inverter without backup, they don't specify the impact of enabling backup mode

**Comment by mletenay** [comment]
@scrhall I've just fixed the house_consumption (will get into v0.9.10), the backup load was indeed missing there.
However I'm now wondering about the total_power and plant_power sensors. The former comes directly from inverter, the latter is calculated as pload + pback_up.
I expect they should report roughly the same numbers.
Can you observe it in real life if it is true ?

**Comment by scrhall** [comment]
![Screenshot_2021-09-12-15-11-13-146_com goodweforphone](https://user-images.githubusercontent.com/5793824/132988924-6de1879c-1ff1-4559-9637-5c29c2d27855.jpg)
![Screenshot_2021-09-12-15-10-19-559_com android chrome](https://user-images.githubusercontent.com/5793824/132988925-4fdb0924-adf7-4f89-ae87-0800525b07a3.jpg)

**Comment by scrhall** [comment]
![Screenshot_2021-09-12-15-11-13-146_com goodweforphone](https://user-images.githubusercontent.com/5793824/132989061-58a7f2ff-9666-48a1-8dfa-7c6775c6cf7c.jpg)
![Screenshot_2021-09-12-15-10-19-559_com android chrome](https://user-images.githubusercontent.com/5793824/132989062-88835733-6b63-4dd8-a52e-24faae9c46ea.jpg)

**Comment by CEF-PHORAM** [comment]
The ES-5048 self-consumption with the output of the BackUp loads active is between **60 to 75** total watts. I have measured it with external instruments.

**Comment by mletenay** [comment]
House consumption fixed in v0.9.0

**Comment by scrhall** [comment]
The solution is not correct, it is not simply adding backup, the backup is already included in a certain way. Now the consumption appears as if adding twice the backup. I had to install the previous version again

**Comment by mletenay** [comment]
I'm not reopening this ticket, since the discussion moved to new one #66.
But I need help with defining proper formula.

**Comment by jebeke65** [comment]
The GW5000S-BP house consumption is much too high, hence not correct. When I check the value during the night, I’m getting around 1500W which is certainly not what is consumed in the house
