### ISSUE TITLE
Inverter_test.py throws a syntax error at line 22 ??

### ISSUE THREAD

**Issue by craigcurtin-dev** [mletenay/home-assistant-goodwe-inverter#43]
Can not run it to verify if GoodWe SBP5000 will respond

Craig

**Comment by mletenay** [comment]
What python version ?

**Comment by craigcurtin-dev** [comment]
2.7.15 throws the error at Line 22
3.6.6 throws error at line 21 - asyncio has not attribute run

Craig

**Comment by craigcurtin-dev** [comment]
aah - its OK - 3.8.1 fixed it

Also note for your list - the GoodWe SBP5000 (AC coupled storage) is not supported.

I suspected this was the case as The matrix from Goodwe shows that Modbus is only supported on RTU 

Craig

**Comment by mletenay** [comment]
Support for BP was added in v0.8.2
