### ISSUE TITLE
ET Powerfactor

### ISSUE THREAD

**Issue by mfaust78** [mletenay/home-assistant-goodwe-inverter#51]
Great addition of the power factor fields:
et.py:
> ...
>         Integer("meter_power_factor1", 20, "Meter Power Factor L1"),
>         Integer("meter_power_factor2", 22, "Meter Power Factor L2"),
>         Integer("meter_power_factor3", 24, "Meter Power Factor L3"),
> ...

But the values should range from -1 to 1. I think a division by 100 would be correct (not a integer value).

**Comment by mletenay** [comment]
Introduced new Decimal sensor type and switched power factors to.
Will get into next release (0.8.6)
