### ISSUE TITLE
House consumption is not correct calculated

### ISSUE THREAD

**Issue by kolossboss** [mletenay/home-assistant-goodwe-inverter#7]
Hi,

I think the `sensor.goodwe_house_consumption` is not correct calculated. 
It should be  `sensor.goodwe_ppv - sensor.goodwe_pbattery1 + sensor.goodwe_pgrid`
![House_con](https://user-images.githubusercontent.com/11015086/94542966-c1aada80-0249-11eb-8d73-60b61482286b.PNG)

Also,
I'm not completly sure what `sensor.goodwe_total_power` is, but I think it should be shown in W and not KW. (I made a  Pull request for this. Not sure if its done right. I'm not a developer ^^)

thanks a lot!

**Comment by mletenay** [comment]
The pull request was merged, thanks.
Regarding the house consumption, I'm really sure.
The formula is at least for the ET inverters correct: 
_pbattery_ is signed value - when charging battery it is negative, when discharging, positive.
_active_power_ (the EzMeter value) is signed as well - negative when importing, positive when exporting to grid.
It is possible the ES/EM inverters provide different values res. sign.
Is _pbattery1_ res. _ibattery1_ always positive or are those signed values depending on charging status ?

**Comment by kolossboss** [comment]
Ah ok, I see the problem here. pbattery1 and ibattery1 are always positiv. 
Maybe you can change the sign depending on battery_mode (2 discharge and 3 charge).
Or you can change the sign in the calculation depending on battery mode.

**Comment by mletenay** [comment]
Seems the ET protocol is a bit smarter than ES/EM.
It would be great if someone can run the inverter_test.py and collect the raw UDP response in various inverter conditions - battery charging/discharging, grid import/export etc.
I will then adjust the code so it provide proper data (and ideally some unit tests).

**Comment by mletenay** [comment]
I have added the signs to ibattery1, pbattery1 and pgrid.
Now they make more sense, are compatible with ET inverters and as consequence provide correct house_consumption.

**Comment by kolossboss** [comment]
Thanks a lot. I try to run the inverter_test.py today.

**Comment by kolossboss** [comment]
Hi,

the calculation is still not correct. When battery is charging pbattery is positiv and when discharging its negativ.

**Comment by mletenay** [comment]
Aaah. You're of course right. I messed the sign in battery values (used same condition as in grid, which is wrong).
Fixed now.
