### ISSUE TITLE
Integration does not show up after 0.9.2

### ISSUE THREAD

**Issue by Simanias** [mletenay/home-assistant-goodwe-inverter#78]
I've just updated to version 0.9.2 and, as according the readme, I have removed the configuration info. But when I try to add the integration via the HA panel, it does not show.

**Comment by mletenay** [comment]
Configuration >> Integrations, lower right corner "+ Add Integration" does not offer you the "Goodwe Inverter" integration ?

**Comment by rivebe** [comment]
@mletenay do I understand correctly that the Home Assistant team is about to add this GoodWe functionality to the list of available integrations in the near future?

**Comment by mletenay** [comment]
Yes, that's correct. 
The integration code is already in review process and if it will finish in time, it could get into next HA 2021.12 release.
