### ISSUE TITLE
MS Inverter not working when upgraded to v0.9.3

### ISSUE THREAD

**Issue by vodopives** [mletenay/home-assistant-goodwe-inverter#86]
Thanks for the integration! 

I am having an issue with the MS Inverter GW8500-MS when upgraded to the v0.9.3 version.

I had it configured to automaticaly discover the inverter type and was working fine on the v0.9.1:

"  - platform: goodwe
    ip_address: 192.168.1.50"

i tried the configuration bellow after upgrading and also it did not work:
"  - platform: goodwe
    ip_address: 192.168.1.50
    #network_timeout: 1
    #network_retries: 3
    #scan_interval: 30
    inverter_type: MS           # One of ET, EH, ES, EM, DT, NS, XS, BP or None to detect inverter type automatically
    #comm_address: 247           # Inverter communication address, 247 for ET/EH inverters 127 for DT/D-NS/XS inverters
    #sensor_name_prefix: GoodWe
    #include_unknown_sensors: false"

I get this error on the Log:

#Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:164
Integration: Sensor (documentation, issues)
First occurred: 17:06:01 (1 occurrences)
Last logged: 17:06:01

The goodwe platform for the sensor integration does not support platform setup. Please remove it from your config.#

Could you take a look if that is something that needs attention please?
Thanks.

**Comment by mletenay** [comment]
After v0.9.3 you should actually remove (or at least comment out) the setup in the yaml file and everything needs to be done via UI only. (It means you have to manually add the inverter via UI after upgrade).
If you did that, is there anything else relevant in the log files ?
