### ISSUE TITLE
Incorrect value for sensor.goodwe_pgrid

### ISSUE THREAD

**Issue by kolossboss** [mletenay/home-assistant-goodwe-inverter#9]
Hi,

I think the `pgrid sensor` did not show the right value. 

As I understand it, the sensor shows the value of `sensor.goodwe_pload` with the sign depending on `sensor.goodwe_work_mode`

Also the sensor work_mode did not change status anymore.

![ongrid](https://user-images.githubusercontent.com/11015086/94916351-d340ec00-04ae-11eb-860b-e13a595b228a.PNG)

**Comment by mletenay** [comment]
Naming is a bit confusing, but no, pgrid and pload are two different measurements.
pgrid is the power (flowing in or out the grid) as reported by EzMeter.
pload is the power inverter is producing for its on-grid side.
pgrid may now be negative/positive, pload is always positive.
The energy mode is again different measurement one of (with weird name).
Look at energy_mode_label sensor, there is human readable label of reported value 2.
One of": 
    0: "Check Mode",
    1: "Wait Mode",
    2: "Normal(On-Grid)",
    4: "Normal(Off-Grid)",
    8: "Flash Mode",
    16: "Fault Mode",
    32: "Battery Standby",
    64: "Battery Charging",
    128: "Battery Discharging",

**Comment by kolossboss** [comment]
Thanks for clarifying this.

But also, the value of `pgrid` probably not correct.
It should be the same value like the `pmeter` in the SEMS integration. And like this in the SEMS Portal. But its not. Its always low then `pmeter`. 

<img width="794" alt="Bildschirmfoto 2020-10-02 um 16 15 33" src="https://user-images.githubusercontent.com/11015086/94933391-9b47a200-04ca-11eb-8be6-453f16872768.png">
<img width="385" alt="Bildschirmfoto 2020-10-02 um 16 14 47" src="https://user-images.githubusercontent.com/11015086/94933403-9da9fc00-04ca-11eb-9b1e-dd31c340bb5e.png">

**Comment by mletenay** [comment]
I'm confused a bit.
From the SEMS picture I would assume the pgrid should be -121, pload = 360 and pbattery1 -24.
What are the reported values ? And which inverter model do you have ?

**Comment by kolossboss** [comment]
Sorry. `PV Leistung von/zu Netz` is the pmeter sensor from the SEMS integration.
My Model is: GW3648-EM

I think pgrid should be -106, but its not.

![Bildschirmfoto 2020-10-02 um 16 55 10](https://user-images.githubusercontent.com/11015086/94937876-76562d80-04d0-11eb-999a-72d596937efd.png)
<img width="841" alt="Bildschirmfoto 2020-10-02 um 16 55 30" src="https://user-images.githubusercontent.com/11015086/94937884-77875a80-04d0-11eb-9631-5412f4596cad.png">

**Comment by mletenay** [comment]
Hmm, those numbers do no match at all.
I can't find problem with the data from the UDP packets and the discrepancies are probably caused by big latency of SEMS.
The time between measurement, its transfer from inverter to sems portal and processing there can be in several seconds or tens of seconds.
If the pv production is volatile (cloudy and/or changes in consumption), those two numbers can differ significantly.
I think we should try to compare the results of sems vs udp again in stable conditions (on sunny day).

**Comment by kolossboss** [comment]
I executed the inverter_test.py to a completely different time.

But the Screens are at the same time, right after refresh. 
In HA I can see the graph. pgrid and pmeter (semsportal) differs over the  whole day on about 100W

**Comment by mletenay** [comment]
I can't explain differences with sems data and there's probably not much we can do. 
But if there is a problem with decoding data from udp packets, the only way to identify them is to compare them with the immediate data from PvMastet app, not sems.
