### ISSUE TITLE
battery percentage?

### ISSUE THREAD

**Issue by bp-ouhaha** [mletenay/home-assistant-goodwe-inverter#90]
I'm using this integration in Home Assistant with great pleasure, for a GoodWe ET invertor with a BYD HVS battery.

It's working very well, also in the new Energy dashboard.

I'm missing only 1 thing: **the battery percentage**!

Thanks in advance, and if I can provide data/help, let me know, I have programming skills.

**Comment by mfaust78** [comment]
On the default Dashboard the Battery percentage does not show up in my Home Assisant, but it is present.
Either in in History, a edited Dashboard or the Developer Tools you can look for "sensor.goodwe_battery_soc" or simply search for SOC (State of Charge).

**Comment by bp-ouhaha** [comment]
you are totally right!

I missed it somehow.

Thanks :)
