### ISSUE TITLE
GW5000L-DT Not Connecting

### ISSUE THREAD

**Issue by Crootie** [mletenay/home-assistant-goodwe-inverter#91]
I am trying to add this to my HA but i keep getting Failed to connect to inverter. I have it connected to the wifi and can access it via the webpage and i can ping it via the network address as well. Anyone have any ideas or is there something i am missing.

Cheers

**Comment by mletenay** [comment]
Are you able to connect to the inverter via the SolarGo mobile app ?
If not, then your inverter may have old ARM firmware - see readme
